blog/urls.py
from django.urls import path
from blog.views import DraftPostsListView, index, post_share, post_comment, post_detail, post_search

app_name = 'blog'

urlpatterns = [
    # path('', IndexListView.as_view(), name='post_list'),
    path('', index, name='post_list'),
    path('search/', post_search, name='post_search'),
    path('draft_list/', DraftPostsListView.as_view(), name='draft_list'),
    path('tag/<slug:tag_slug>/', index, name='post_list_by_tag'),
    path('blog/<int:year>/<int:month>/<int:day>/<slug:post>', post_detail, name='post_detail'),
    path('<int:post_id>/share/', post_share, name='post_share'),
    path('<int:post_id>/comment/', post_comment, name='post_comment'),
]

config/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class DraftManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.DRAFT)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Черновик'
        PUBLISHED = 'PB', 'Опубликовано'

    title = models.CharField(max_length=250, verbose_name='Название')
    slug = models.SlugField(max_length=250, unique_for_date='publish', verbose_name='URl')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts', verbose_name='Автор')
    body = models.TextField(verbose_name='Содержание')
    publish = models.DateTimeField(default=timezone.now, verbose_name='Дата публикации')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    status = models.CharField(max_length=2, choices=Status.choices,
                              default=Status.DRAFT, verbose_name='Статус публикации')

    objects = models.Manager()
    published = PublishedManager()
    draft = DraftManager()

    class Meta:

        ordering = ['-publish']

        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.month,
                                                 self.publish.day,
                                                 self.slug])

blog/models/comment.py
from django.db import models


class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='comments', verbose_name='Пост')
    name = models.CharField(max_length=80, verbose_name='Заголовок')
    email = models.EmailField(verbose_name='Email')
    body = models.TextField(verbose_name='Содержание')
    created = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='Дата обновления', auto_now=True)
    active = models.BooleanField(verbose_name='Отображение', default=True)

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['created']
        indexes = [models.Index(fields=['created']), ]

    def __str__(self):
        return f"Комментарий от {self.name} на {self.post}"

blog/models/post.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class DraftManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.DRAFT)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Черновик'
        PUBLISHED = 'PB', 'Опубликовано'

    title = models.CharField(max_length=250, verbose_name='Название')
    slug = models.SlugField(max_length=250, unique_for_date='publish', verbose_name='URl')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts', verbose_name='Автор')
    body = models.TextField(verbose_name='Содержание')
    publish = models.DateTimeField(default=timezone.now, verbose_name='Дата публикации')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    status = models.CharField(max_length=2, choices=Status.choices,
                              default=Status.DRAFT, verbose_name='Статус публикации')

    tags = TaggableManager()

    objects = models.Manager()
    published = PublishedManager()
    draft = DraftManager()

    class Meta:

        ordering = ['-publish']

        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.month,
                                                 self.publish.day,
                                                 self.slug])

blog/forms.py
from django import forms
from blog.models import Comment


class EmailPostForm(forms.Form):

    name = forms.CharField(max_length=25, label='Имя отправителя')
    email = forms.EmailField(label='Адрес электронной почты отправителя')
    to = forms.EmailField(label='Адрес электронной почты получателя')
    comments = forms.CharField(required=False, label='Сообщение', widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body',)


class SearchForm(forms.Form):
    query = forms.CharField(label='Ваш запрос')

blog/views.py
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from django.views.generic import ListView
from taggit.models import Tag
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from .forms import EmailPostForm, CommentForm, SearchForm
from .models import Post


# class IndexListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/index.html'


def index(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    #  Постраничная разбивка с 3 постами на страницу
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)

    except PageNotAnInteger:
        #  Если page_number не целое число, то выдать первую страницу
        posts = paginator.page(1)

    except EmptyPage:
        # Если page_number находится вне диапазона, то выдать последнюю страницу результатов
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'blog/post/index.html',
                  {'posts': posts,
                   'tag': tag})


class DraftPostsListView(ListView):
    queryset = Post.draft.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/draft_list.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    # Список активных комментариев к этому посту
    comments = post.comments.filter(active=True)

    # Форма для комментирования пользователями
    form = CommentForm()

    # Список похожих постов
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:2]

    return render(request, 'blog/post/detail.html', {
        'post': post,
        'comments': comments,
        'form': form,
        'similar_posts': similar_posts})


def post_share(request, post_id):
    # Извлечь пост по идентификатору id
    post = get_object_or_404(Post, pk=post_id, status=Post.Status.PUBLISHED)

    sent = False

    if request.method == 'POST':
        # Форма была передана на обработку
        form = EmailPostForm(request.POST)

        if form.is_valid():

            # Поля формы успешно прошли валидацию
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} рекомендует вам прочитать статью '{post.title}'"
            message = f"Читать '{post.title}' по ссылке {post_url}\n\n" \
                      f"{cd['name']} также написал: {cd['comments']}"
            send_mail(subject, message, 'alexandr.abramovv@gmail.com', [cd['to']])

            # отправить электронное письмо
            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id, status=Post.Status.PUBLISHED)
    comment = None

    # Комментарий был отправлен
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Создать объект класса Comment, не сохраняя его в базе данных
        comment = form.save(commit=False)

        # Назначить пост комментарию
        comment.post = post

        # Сохранить комментарий в базе данных
        comment.save()

    return render(request, 'blog/post/comment.html', {'post': post,
                                                      'form': form,
                                                      'comment': comment})


def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)

        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body', config='russian')

            search_query = SearchQuery(query, config='russian')
            results = Post.published.annotate(search=search_vector, rank=SearchRank(search_vector, search_query)
                                              ).filter(search=search_query).order_by('-rank')

    return render(request, 'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

blog/templates/blog/post/comment.html
{% extends "base.html" %}
{% block title %}
Add a comment
{% endblock %}
{% block content %}
    {% if comment %}
        <h2>Ваш комментарий опубликован</h2>
        <p><a href="{{ post.get_absolute_url }}">Вернуться к посту</a></p>
    {% else %}
        {% include "blog/post/includes/inc_comment_form.html" %}
    {% endif %}
{% endblock %}

blog/templates/blog/post/detail.html
{% extends "base.html" %}
{% block title %}
{{ post.title }}
{% endblock %}
{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">
    {% if post.status == 'PB' %}

    Опубликовано {{ post.publish }} by {{ post.author }}

    {% else %}
    Создан {{ post.created }} by {{ post.author }} <br>
    Последнее изменение {{ post.updated }} by {{ post.author }}

    {% endif %}
</p>
{{ post.body|linebreaks }}
{% if post.status == 'PB' %}
<p>
    <a href="{% url 'blog:post_share' post.id %}">Поделиться постом</a>
</p>

<h2>Вас может заинтересовать:</h2>
{% for post in similar_posts %}
    <p>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
{% empty %}
    Мы не смогли подобрать для вас похожие статьи
{% endfor %}
<p>
    <a class="link" href="{% url 'blog:post_list' %}">Назад</a>
</p>

{% with comments.count as total_comments %}
    <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
{% endwith %}

{% for comment in comments %}
<div class="comment">
    <p class="info">
        Комментарий {{ forloop.counter }} к посту '{{ comment.name }}'
        {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
</div>
{% empty %}
<p>Комментариев нет, вы будете первым!</p>
{% endfor %}
{% include "blog/post/includes/inc_comment_form.html" %}

{% else %}
<p><a class="link" href="{% url 'blog:draft_list' %}">Назад</a></p>

{% endif %}
{% endblock %}

blog/templates/blog/post/draft_list.html
{% extends "base.html" %}
{% block title %}
My Blog
{% endblock %}
{% block content %}
<h1>Дачный developing</h1>
{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
    </a>
</h2>
<p class="date">
    Создан {{ post.created }} by {{ post.author }} <br>
</p>
{{ post.body|truncatewords:30|linebreaks }}
{% endfor %}
{% include "pagination.html" with page=page_obj %}
{% endblock %}

blog/templates/blog/post/index.html
{% extends "base.html" %}
{% block title %}My Blog{% endblock %}

{% block content %}
<h1>Дачный developing</h1>
{% if tag %}
    <h2>Посты по тегу: "{{ tag.name }}"</h2>
{% endif %}

{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
    </a>
</h2>
<p class="tags">
    Теги:
    {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
            {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
    {% endfor %}

</p>
<p class="date">
    Опубликовано {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|truncatewords:30|linebreaks }}
{% endfor %}
{% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/latest_post.html
<ul>
    {% for post in latest_post %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

blog/templates/blog/post/search.html
{% extends "base.html" %}
{% block title %}Поиск{% endblock %}
{% block content %}
{% if query %}
<h1>Поиск по ключевому слову "{{ query }}"</h1>
<h3>
    {% with results.count as total_results %}
    Найдено {{ total_results }} статьи
    {% endwith %}
</h3>
{% for post in results %}
<h4>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
    </a>
</h4>
{{ post.body|truncatewords:12 }}
{% empty %}
<p>К сожалению, по вашему запросу ничего не найдено.</p>
{% endfor %}
<p><a href="{% url 'blog:post_search' %}">Повторить поиск</a></p>
{% else %}
<h1>Поиск статей</h1>
<form method="get">
    {{ form.as_p }}
    <input type="submit" value="Search">

</form>
{% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "base.html" %}
{% block title %}
Поделиться
{% endblock %}
{% block content %}
{% if sent %}
<h1>Письмо успешно отправлено</h1>
<p>
    "{{ post.title }}" было успешно отправлено
    {{ form.cleaned_data.to }}.
<p><a class="link" href="{% url 'blog:post_list' %}">К статьям</a></p>

{% else %}
<h2>Поделиться постом "{{ post.title }}" по электронной почте</h2>

<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Поделиться">
</form>

{% endif %}
{% endblock %}